Repository m3ntorship/charity, pull requests merged in 2020-06, with the labels that each got.

#373 Introducing react redux
  package.json
  src/components/Numbers/index.jsx
  src/components/Testimonials/index.js
  src/containers/Home/index.jsx
  src/containers/Home/numbers.jsx
  src/containers/Home/testimonials.jsx
  src/index.js
  src/store/actionTypes/index.js
  src/store/actions/index.js
  src/store/actions/numbers.js
  src/store/actions/testimonials.js
  src/store/index.js
  src/store/reducers/numbers.js
  src/store/reducers/testimonials.js
  yarn.lock
Labels: PR: reviewed-approved, Ready For Review

#395 Redux/activities
  src/components/Activities/index.jsx
  src/containers/Home/activities.js
  src/containers/Home/index.jsx
  src/store/actionTypes/index.js
  src/store/actions/activities.js
  src/store/actions/index.js
  src/store/index.js
  src/store/reducers/activities.js
Labels: PR: reviewed-approved, Ready For Review

#394 Feature/redux/welcome
  src/components/Welcome/index.jsx
  src/containers/Home/index.jsx
  src/containers/Home/welcome.jsx
  src/store/actionTypes/index.js
  src/store/actions/index.js
  src/store/actions/welcome.js
  src/store/index.js
  src/store/reducers/welcome.js
Labels: PR: reviewed-approved

#399 Feature/redux/contact info
  src/components/ContactInfo/index.jsx
  src/containers/Home/contactInfo.jsx
  src/containers/Home/footer.js
  src/containers/Home/index.jsx
  src/store/actionTypes/index.js
  src/store/actions/contactInfo.js
  src/store/actions/footer.js
  src/store/actions/index.js
  src/store/actions/social.js
  src/store/index.js
  src/store/reducers/contact.js
  src/store/reducers/footer.js
  src/store/reducers/social.js
Labels: PR: reviewed-approved

#398 Feature/redux/work style
  src/components/WorkStyle/index.jsx
  src/containers/Home/index.jsx
  src/containers/Home/workStyle.jsx
  src/store/actionTypes/index.js
  src/store/actions/index.js
  src/store/actions/workStyle.js
  src/store/index.js
  src/store/reducers/workStyle.js
Labels: PR: reviewed-approved

#396 Feature/redux/causes
  src/components/Causes/index.jsx
  src/containers/Home/causes.jsx
  src/containers/Home/index.jsx
  src/store/actionTypes/index.js
  src/store/actions/causes.js
  src/store/actions/index.js
  src/store/index.js
  src/store/reducers/causes.js
Labels: PR: reviewed-approved

#400 Redux/featured banner
  src/components/FeaturedBanner/index.jsx
  src/containers/Home/featuredBanner.js
  src/containers/Home/index.jsx
  src/store/actionTypes/index.js
  src/store/actions/featuredBanner.js
  src/store/actions/index.js
  src/store/index.js
  src/store/reducers/featuredBanner.js
Labels: PR: reviewed-approved

#401 Feature/redux/articles
  src/containers/Articles/ArticlesList.jsx
  src/containers/Articles/index.jsx
  src/store/actionTypes/index.js
  src/store/actions/Articles.js
  src/store/actions/index.js
  src/store/index.js
  src/store/reducers/articles.js
Labels: PR: reviewed-approved, Ready For Review

#403 Feature/redux/pages
  src/App.js
  src/components/ArticleBanner/index.js
  src/components/VolunteeringBanner/index.jsx
  src/containers/Articles/index.jsx
  src/store/actionTypes/index.js
  src/store/actions/index.js
  src/store/actions/pages.js
  src/store/index.js
  src/store/reducers/pages.js
Labels: PR: partially-approved, Ready For Review

#404 Redux/footer
  src/App.js
  src/components/Footer/index.jsx
  src/containers/Home/index.jsx
  src/containers/layout/footer.js
  src/store/actionTypes/index.js
  src/store/actions/index.js
  src/store/index.js
Labels: PR: reviewed-approved, Ready For Review

#397 Feature/redux upcoming events
  src/components/UpcomingEvents/index.jsx
  src/containers/Home/index.jsx
  src/store/actionTypes/index.js
  src/store/actions/featuredCause.js
  src/store/actions/index.js
  src/store/actions/upcomingEvents.js
  src/store/index.js
  src/store/reducers/featuredCause.js
  src/store/reducers/upcomingEvents.js
Labels: PR: reviewed-approved, Ready For Review

#393 Redux header carousel
  src/components/HeaderCarousel/index.js
  src/containers/Home/headercarousel.jsx
  src/containers/Home/index.jsx
  src/store/actionTypes/index.js
  src/store/actions/headercarousel.js
  src/store/actions/index.js
  src/store/index.js
  src/store/reducers/headercarousel.js
Labels: PR: reviewed-approved, Ready For Review

#405 computed main navigation links from redux state (Pages)
  src/components/MainNavigation/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#406 Redux/logo
  src/App.js
  src/components/Header/index.jsx
  src/components/Logo/index.jsx
  src/components/MainNavigation/index.jsx
  src/containers/layout/logo.js
  src/store/actionTypes/index.js
  src/store/actions/index.js
  src/store/actions/logo.js
  src/store/index.js
  src/store/reducers/logo.js
Labels: PR: reviewed-approved, Ready For Review

#411 feature/sanitizing Contact data
  src/store/actions/contactInfo.js
  src/store/reducers/contact.js
Labels: PR: reviewed-approved, Ready For Review

#415 feature/sanitizing Work Style data
  src/store/actions/workStyle.js
  src/store/reducers/workStyle.js
Labels: PR: reviewed-approved, Ready For Review

#430 Feature/connect/sponsers
  src/components/Sponsers/img/envato-dark.png
  src/components/Sponsers/img/envato-light.png
  src/components/Sponsers/index.jsx
  src/containers/Home/index.jsx
  src/containers/Home/sponsers.jsx
  src/store/actionTypes/index.js
  src/store/actions/index.js
  src/store/actions/sponsers.js
  src/store/index.js
  src/store/reducers/sponsers.js
Labels: PR: reviewed-approved, Ready For Review

#429 Feature/redux connect activities
  src/containers/Home/activities.js
  src/containers/Home/activities.jsx
  src/containers/Home/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#426 Feature/redux/recent articles
  src/components/ArticlePageContent/index.jsx
  src/components/RecentArticles/index.jsx
  src/containers/Articles/index.jsx
  src/containers/Articles/recentArticles.jsx
Labels: PR: reviewed-approved, Ready For Review

#434 Feature/use casues ct to get featured cause
  src/components/FeaturedCause/index.jsx
  src/components/UpcomingEvents/index.jsx
  src/containers/Home/index.jsx
  src/store/actionTypes/index.js
  src/store/actions/featuredCause.js
  src/store/actions/index.js
  src/store/index.js
  src/store/reducers/featuredCause.js
Labels: PR: reviewed-approved, Ready For Review

#428 Redux/Connect news articles
  src/components/NewsAndArticles/index.jsx
  src/containers/Home/index.jsx
  src/containers/Home/news&articles.js
  src/store/actionTypes/index.js
  src/store/actions/index.js
  src/store/actions/news&articles.js
  src/store/index.js
  src/store/reducers/news&articles.js
Labels: PR: reviewed-approved, Ready For Review

#431 Redux/main contact
  src/App.js
  src/components/Header/index.jsx
  src/components/MainContact/index.jsx
  src/containers/layout/mainContact.js
  src/store/actionTypes/index.js
  src/store/actions/index.js
  src/store/actions/mainContact.js
  src/store/index.js
  src/store/reducers/mainContactReducer.js
Labels: PR: reviewed-approved, Ready For Review

#407 Feature/sanitizing causes data
  src/components/Causes/index.jsx
  src/store/actions/causes.js
  src/store/reducers/causes.js
Labels: PR: partially-approved, Ready For Review

#413 feature/sanitizing Social data
  src/components/ContactInfo/index.jsx
  src/store/actions/social.js
  src/store/reducers/social.js
Labels: PR: partially-approved, Ready For Review

#438 data sanitization: Header Carousel
  src/store/actions/headercarousel.js
Labels: PR: reviewed-approved

#439 Bug/articles news component missing desc
  src/components/NewsAndArticles/index.jsx
  src/store/actions/news&articles.js
Labels: PR: reviewed-approved, Ready For Review

#447 Feature/sanitized featured banner
  src/components/FeaturedBanner/index.jsx
  src/store/actions/activities.js
  src/store/actions/featuredBanner.js
  {
Labels: PR: reviewed-approved, Ready For Review

#445 sanitize activities component
  src/components/Activities/index.jsx
  src/store/actions/activities.js
Labels: PR: reviewed-approved, Ready For Review

#452 Feature/sanitizing welcome section
  src/components/Welcome/index.jsx
  src/store/actions/welcome.js
  src/store/reducers/welcome.js
Labels: PR: reviewed-approved, Ready For Review

#453 remove mainContactsReducer.js~HEAD file
  src/store/reducers/mainContactReducer.js~HEAD
Labels: PR: reviewed-approved, Ready For Review

#456 Feature/redux/contact top
  src/App.js
  src/components/ContactTop/index.jsx
  src/components/Header/index.jsx
  src/components/HeaderCarousel/index.js
  src/containers/layout/contactTop.js
  src/store/actionTypes/index.js
  src/store/actions/contactTop.js
  src/store/actions/headercarousel.js
  src/store/actions/index.js
  src/store/index.js
  src/store/reducers/contactTop.js
Labels: PR: reviewed-approved, Ready For Review

#451 Sanitizing Articles Data
  src/App.js
  src/components/ArticleModel/index.js
  src/components/NewsAndArticles/index.jsx
  src/components/RecentArticles/index.jsx
  src/components/shared/ListItemWithThumbnail/index.jsx
  src/containers/Articles/index.jsx
  src/containers/Home/news&articles.js
  src/store/actions/Articles.js
  src/store/reducers/articles.js
Labels: PR: reviewed-approved, Ready For Review

#444 New HeaderNavigation
  src/components/ArticleBanner/index.js
  src/components/ContactInfo/styles.css
  src/components/Header/index.jsx
  src/components/HeaderNavigation/index.jsx
  src/components/HeaderNavigation/style.css
  src/components/Logo/index.jsx
  src/components/MainNavigation/ContentLoader/index.jsx
  src/components/MainNavigation/index.jsx
  src/components/MainNavigation/style.css
  src/components/NavigationLink/index.jsx
  src/components/NavigationLink/style.css
  src/containers/Home/contactInfo.jsx
  src/containers/Home/index.jsx
  src/containers/layout/HeaderNavigation.jsx
  src/containers/layout/footer.js
  src/containers/layout/mainContact.js
  src/store/actionTypes/index.js
  src/store/actions/contactInfo.js
  src/store/actions/index.js
  src/store/actions/mainContact.js
  src/store/index.js
  src/store/reducers/contact.js
  src/stories/HeaderNavigation.stories.js
  src/stories/MainNavigation.stories.js
Labels: PR: unreviewed, Ready For Review
