Repository m3ntorship/charity, pull requests merged in 2020-05, with the labels that each got.

#63 create a sponser react component
  src/App.js
  src/components/sponsers/img/envato-dark.png
  src/components/sponsers/img/envato-light.png
  src/components/sponsers/index.jsx
  src/components/sponsers/styles.css
  src/css/original_assets/img/work-style/01.svg
  src/css/original_assets/img/work-style/02.svg
  src/css/original_assets/img/work-style/03.svg
  src/css/original_assets/img/work-style/04.svg
Labels: PR: partially-approved, PR: reviewed-approved

#78 Adjusted the secondary link to pull its own data from the backend
  src/components/MainNavigation/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#71 Upcoming events card
  src/App.js
  src/components/UpcomingEvents/styles.css
  src/components/UpcomingEventsCard/img/bg_2.png
  src/components/UpcomingEventsCard/index.jsx
  src/components/UpcomingEventsCard/style.css
  src/css/original_assets/upcoming-events.css
  yarn.lock
Labels: PR: partially-approved, Ready For Review

#69 News and Articles component
  src/App.js
  src/components/NewsAndArticles/index.jsx
  src/components/NewsAndArticles/styles.css
Labels: PR: unreviewed, Ready For Review

#77 React footer
  src/App.js
  src/components/Footer/about.jsx
  src/components/Footer/articles.jsx
  src/components/Footer/index.jsx
  src/components/Footer/links.jsx
  src/components/Footer/newsletter.jsx
Labels: PR: partially-approved, Ready For Review

#81 Remove repeated workstyle section
  src/App.js
Labels: PR: reviewed-approved

#82 Feature/testimonials react
  package.json
  src/App.js
  src/components/Testimonials/img/blocks.png
  src/components/Testimonials/index.js
  src/components/Testimonials/style.css
  src/css/original_assets/feedback.css
Labels: PR: reviewed-approved

#83 Fixing navigation links
  src/components/NavigationLink/index.jsx
  src/components/NavigationLink/style.css
Labels: PR: reviewed-approved

#88 Feature/header carousel
  src/components/Header/index.jsx
  src/components/HeaderCarousel/index.js
  src/components/HeaderCarousel/styles.css
  src/components/MainNavigation/index.jsx
  src/components/Welcome/styles.css
Labels: PR: reviewed-approved, Ready For Review

#87 Fix upcoming events styles bugs
  src/components/UpcomingEvents/index.jsx
  src/components/UpcomingEvents/styles.css
Labels: PR: reviewed-approved

#94 Fix news and articles
  src/components/NewsAndArticles/index.jsx
  src/components/NewsAndArticles/styles.css
Labels: PR: reviewed-approved, Ready For Review

#92 fix hover and color style
  src/components/ContactInfo/styles.css
Labels: PR: reviewed-approved, Ready For Review

#99 Upcoming Events section Fixing styles.
  src/components/UpcomingEvents/index.jsx
  src/components/UpcomingEvents/styles.css
  src/components/UpcomingEventsCard/index.jsx
  src/components/UpcomingEventsCard/style.css
Labels: PR: reviewed-approved

#102 Top contact section navbar
  package.json
  src/components/ContactTop/index.jsx
  src/components/ContactTop/style.scss
  src/components/MainContact/index.jsx
  src/components/MainContact/styles.scss
  src/components/MainNavigation/index.jsx
  src/components/MainNavigation/style.css
  yarn.lock
Labels: PR: reviewed-approved

#100 Fix how we work
  .gitignore
  package.json
  src/components/WorkStyle/index.jsx
  src/components/WorkStyle/styles.css
  src/components/WorkStyleCard/index.jsx
  yarn.lock
Labels: PR: reviewed-approved, Ready For Review

#104 Hotfix/footer sponses sections
  src/components/ContactInfo/index.jsx
  src/components/ContactInfo/styles.css
  src/components/Footer/About/index.jsx
  src/components/Footer/About/style.css
  src/components/Footer/Articles/index.jsx
  src/components/Footer/Articles/style.css
  src/components/Footer/Links/index.jsx
  src/components/Footer/NewsLetter/index.jsx
  src/components/Footer/NewsLetter/style.css
  src/components/Footer/index.jsx
  src/components/Sponsers/index.jsx
  src/components/Sponsers/styles.css
Labels: PR: reviewed-approved

#98 Fix Numbers issues
  src/components/Numbers/index.jsx
  src/components/Numbers/style.css
Labels: PR: reviewed-approved

#105 Fix Popular causes styles
  src/components/Causes/index.jsx
  src/components/Causes/style.css
Labels: PR: reviewed-approved

#108 Fix Featured Banner styles
  src/components/FeaturedBanner/index.jsx
  src/components/FeaturedBanner/styles.css
Labels: PR: reviewed-approved, Ready For Review

#114 Resonsive Global
  src/css/global.css
Labels: PR: reviewed-approved

#109 Fix spacing in News
  src/components/NewsAndArticles/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#120 Purgecss working in production only
  config-overrides.js
Labels: PR: reviewed-approved

#125 Responsive top contact
  src/components/ContactTop/index.jsx
  src/components/ContactTop/style.scss
  src/components/Header/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#115 implement upcoming events section to be responsive
  src/components/UpcomingEvents/index.jsx
  src/components/UpcomingEvents/styles.css
  src/components/UpcomingEventsCard/index.jsx
Labels: PR: reviewed-approved

#110 Re-Build ContactTop Social Icons
  package.json
  src/components/ContactTop/index.jsx
  src/components/ContactTop/style.scss
Labels: PR: partially-approved, Ready For Review

#118 Responsive Testimonials Section
  src/components/Testimonials/index.js
  src/components/Testimonials/style.css
  src/components/WorkStyle/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#131 Responsive footer contact info sponsers
  src/components/ContactInfo/index.jsx
  src/components/ContactInfo/styles.css
  src/components/Footer/About/index.jsx
  src/components/Footer/Articles/index.jsx
  src/components/Footer/Links/index.jsx
  src/components/Footer/NewsLetter/index.jsx
  src/components/Footer/index.jsx
  src/components/Sponsers/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#126 Feature/responsive featured banner
  src/components/FeaturedBanner/index.jsx
  src/components/FeaturedBanner/styles.css
Labels: PR: reviewed-approved, Ready For Review

#135 fix contact top section
  src/components/MainContact/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#133 responsive Numbers section
  src/components/Numbers/index.jsx
  src/components/Numbers/style.css
Labels: PR: reviewed-approved, Ready For Review

#132 make main carousel responsive
  src/components/HeaderCarousel/index.js
  src/components/HeaderCarousel/styles.css
Labels: PR: reviewed-approved

#137 Feature/responsive how we work
  src/components/WorkStyle/index.jsx
  src/components/WorkStyle/styles.css
  src/components/WorkStyleCard/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#134 Responsive: Popular Causes
  src/components/Causes/index.jsx
  src/components/Causes/style.css
  src/components/Causes/useMedia.jsx
Labels: PR: reviewed-approved, Ready For Review

#138 Responsive activities section
  src/components/Activities/index.jsx
  src/components/Activities/styles.css
Labels: PR: reviewed-approved, Ready For Review

#144 Responsive fixing logo main contact
  src/components/Logo/index.jsx
  src/components/Logo/styles.scss
  src/components/MainContact/index.jsx
  src/components/MainContact/styles.scss
Labels: PR: reviewed-approved, Ready For Review

#143 Responsiveness Bugfix: Header Section
  src/components/HeaderCarousel/index.js
Labels: PR: reviewed-approved

#117 Feature/responsive welcome
  config-overrides.js
  src/App.js
  src/components/Welcome/index.jsx
  src/components/Welcome/styles.css
  tailwind.config.js
Labels: PR: reviewed-approved

#146 Bugfix/Activities section responsive
  src/components/Activities/index.jsx
Labels: PR: reviewed-approved

#147 Fix/upcoming events section
  src/components/UpcomingEvents/index.jsx
  src/components/UpcomingEvents/styles.css
  src/components/UpcomingEventsCard/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#130 feature/responsive-news
  src/components/NewsAndArticles/index.jsx
  src/components/NewsAndArticles/styles.css
Labels: PR: reviewed-approved, Ready For Review

#145 Feature/responsive nav bar enhancement
  src/components/HeaderCarousel/index.js
  src/components/MainNavigation/index.jsx
  src/components/MainNavigation/style.css
  src/components/NavigationLink/index.jsx
Labels: PR: reviewed-approved

#150 feature-fix/responsive-welcome Bug:768
  src/components/Welcome/styles.css
Labels: PR: partially-approved

#166 introduce react content loader
  package.json
Labels: PR: reviewed-approved

#168 Causes loader
  src/components/Causes/index.jsx
  yarn.lock
Labels: PR: reviewed-approved, Ready For Review

#169 Content loader contact top
  src/components/ContactInfo/index.jsx
  src/components/ContactTop/ContentLoader/index.jsx
  src/components/ContactTop/index.jsx
  src/components/Logo/ContentLoader/Index.jsx
  src/components/Logo/index.jsx
Labels: PR: reviewed-approved

#171 News and articles loader
  src/components/Causes/index.jsx
  src/components/NewsAndArticles/index.jsx
Labels: PR: reviewed-approved

#170 content-loader-feautred-banner
  src/components/FeaturedBanner/ContentLoader/index.jsx
  src/components/FeaturedBanner/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#167 Hotfix/fix reponsive issues navbar
  src/components/MainNavigation/style.css
Labels: PR: reviewed-approved, Ready For Review

#174 Welcome section Loader
  src/components/Welcome/MyLoader.jsx
  src/components/Welcome/index.jsx
  src/components/WorkStyle/styles.css
Labels: PR: reviewed-approved

#191 Sponsers loader and hooks
  src/components/Sponsers/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#193 Feature/upcoming events loader
  src/components/UpcomingEvents/MyLoader.jsx
  src/components/UpcomingEvents/index.jsx
  src/components/Welcome/MyLoader.jsx
  src/components/Welcome/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#190 Loading content( Activities section)
  src/components/Activities/ActivitiesContentLoading/index.jsx
  src/components/Activities/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#194 use hooks in news and articles
  src/components/NewsAndArticles/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#196 Feature/footer usehooks
  src/components/Footer/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#197 Hooks work style
  src/components/WorkStyle/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#200 use hooks in numbers section
  src/components/Numbers/index.jsx
Labels: PR: reviewed-approved

#201 Feature/numbers loader
  src/components/Numbers/MyLoader.jsx
  src/components/Numbers/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#198 use hooks in testimonial ( feedback ) section
  src/components/Testimonials/index.js
Labels: PR: reviewed-approved, Ready For Review

#206 use hooks in welcome section
  src/components/Welcome/index.jsx
Labels: PR: reviewed-approved

#209 Feature/featured banner usehooks
  src/components/FeaturedBanner/ContentLoader/index.jsx
  src/components/FeaturedBanner/index.jsx
  src/components/Footer/index.jsx
Labels: PR: reviewed-approved

#208 introduce react observer
  package.json
Labels: PR: reviewed-approved, Ready For Review, dependencies

#207 Feature/footer content laoding
  src/components/Footer/FooterContentLoading/index.jsx
  src/components/Footer/index.jsx
Labels: PR: reviewed-approved

#151 feature-fix/responsive-welcome fix 768 bug
  src/components/Welcome/index.jsx
  src/components/Welcome/styles.css
  tailwind.config.js
  yarn.lock
Labels: PR: reviewed-approved, Ready For Review

#217 Feature/animate numbers
  src/components/Numbers/index.jsx
Labels: PR: reviewed-approved

#216 Animation/work style
  src/components/Causes/style.css
  src/components/Testimonials/style.css
  src/components/WorkStyle/index.jsx
  src/components/WorkStyleCard/index.jsx
Labels: PR: reviewed-approved

#218 Feature/loader testmonials
  src/components/Testimonials/MyLoader.jsx
  src/components/Testimonials/index.js
  src/components/Testimonials/style.css
Labels: PR: reviewed-approved

#222 Feature/animation activities
  src/components/Testimonials/MyLoader.jsx
  src/components/Testimonials/index.js
  src/components/Testimonials/style.css
Labels: PR: unreviewed

#215 Feature/Upcoming Events Animation
  src/components/UpcomingEvents/index.jsx
  src/components/UpcomingEventsCard/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#192 Content loader header carousel
  src/components/HeaderCarousel/ContentLoader/index.jsx
  src/components/HeaderCarousel/index.js
  src/components/HeaderCarousel/styles.css
Labels: PR: reviewed-approved

#225 Feature/integrate storybook with postcss tailwind purgecss
  .storybook/main.js
  .storybook/preview-body.html
  .storybook/preview-head.html
  .storybook/preview.js
  config-overrides.js
  config-webpack-postcss.js
  src/stories/1-Heading.stories.js
  src/stories/2-WorkStyle.stories.js
  src/stories/styles.css
Labels: PR: reviewed-approved

#224 Hooks header carousel
  src/components/HeaderCarousel/index.js
  src/components/HeaderCarousel/styles.css
Labels: PR: reviewed-approved

#226 Feature/welcome animation
  public/index.html
  src/Helpers/useMedia.jsx
  src/components/Causes/index.jsx
  src/components/UpcomingEvents/index.jsx
  src/components/UpcomingEventsCard/index.jsx
  src/components/Welcome/index.jsx
  src/css/global.css
Labels: PR: reviewed-approved, Ready For Review

#227 Bugfix/Upcoming Events Animation
  src/components/UpcomingEvents/index.jsx
  src/components/UpcomingEventsCard/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#219 Featured Banner Animation
  src/components/FeaturedBanner/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#199 useHooks: Contact Top
  src/components/ContactTop/index.jsx
Labels: PR: partially-approved

#232 Feature/use hooks main navigation
  src/components/MainNavigation/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#238 Feature/news articles animation
  src/components/ContactTop/index.jsx
  src/components/Heading/index.jsx
  src/components/NewsAndArticles/index.jsx
  src/components/NewsAndArticles/myLoader.jsx
Labels: PR: reviewed-approved, Ready For Review

#240 Feature/causes animation
  src/components/Causes/index.jsx
  src/components/Causes/myLoader.jsx
  src/components/Heading/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#233 Animate: Footer
  src/components/Footer/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#234 Animate: main slider
  src/components/HeaderCarousel/index.js
Labels: PR: reviewed-approved, Ready For Review

#261 Bugfix/heading memory leak
  src/components/Causes/index.jsx
  src/components/Heading/index.jsx
  src/components/NewsAndArticles/index.jsx
  src/components/Welcome/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#283 navbar content loader
  src/components/ContactTop/ContentLoader/index.jsx
  src/components/ContactTop/index.jsx
  src/components/MainNavigation/ContentLoader/index.jsx
  src/components/MainNavigation/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#285 Bugfix/multiple fixes
  src/components/Causes/index.jsx
  src/components/ContactTop/index.jsx
  src/components/Footer/index.jsx
  src/components/Logo/ContentLoader/Index.jsx
  src/components/Logo/index.jsx
  src/components/MainContact/ContentLoader/index.jsx
  src/components/MainContact/index.jsx
  src/components/NewsAndArticles/index.jsx
Labels: PR: unreviewed

#262 Feature/sponsers story
  src/App.js
  src/components/Sponsers/index.jsx
  src/stories/3-Sponsers.stories.js
Labels: PR: reviewed-approved

#287 temporary fix for workstyle animation in mobile
  src/components/WorkStyle/index.jsx
Labels: PR: reviewed-approved

#223 Animate: Activities
  src/components/Activities/index.jsx
  src/components/HeaderCarousel/index.js
  src/components/MainNavigation/index.jsx
  src/components/Testimonials/MyLoader.jsx
Labels: PR: reviewed-approved, Ready For Review

#290 fixed background bug in large screens
  src/components/Causes/index.jsx
Labels: PR: reviewed-approved

#294 StoryBook: Footer
  src/App.js
  src/components/Footer/index.jsx
  src/stories/8-Footer.stories.js
Labels: PR: reviewed-approved, Ready For Review

#297 Upcoming Events Card story book
  src/components/UpcomingEvents/index.jsx
  src/components/UpcomingEventsCard/MyLoader.jsx
  src/components/UpcomingEventsCard/index.jsx
  src/stories/19-UpcomingEventsCard.stories.js
Labels: PR: reviewed-approved, Ready For Review

#293 StoryBook: Activities
  src/App.js
  src/components/Activities/index.jsx
  src/stories/7-Activities.stories.js
Labels: PR: reviewed-approved, Ready For Review

#289 Feature/story numbers test
  src/App.js
  src/components/Numbers/index.jsx
  src/stories/Numbers.stories.js
Labels: PR: reviewed-approved, Ready For Review

#231 contact top story and error handling
  src/components/ContactTop/index.jsx
  src/components/ContactTop/style.scss
  src/components/Header/index.jsx
  src/components/WorkStyle/index.jsx
  src/stories/2-WorkStyle.stories.js
  src/stories/3-ContactTop.stories.js
  src/stories/contactTopData.json
Labels: PR: reviewed-approved, Ready For Review

#292 Feature/causes storybook
  src/App.js
  src/components/Causes/index.jsx
  src/stories/5-Causes.stories.js
Labels: PR: reviewed-approved, Ready For Review

#298 Feature/storybook main contact
  src/components/Header/index.jsx
  src/components/MainContact/index.jsx
  src/stories/MainContacts.stories.js
Labels: PR: reviewed-approved, Ready For Review

#291 StoryBook: FeaturedBanner
  src/App.js
  src/components/FeaturedBanner/index.jsx
  src/stories/6-FeaturedBanner.stories.js
Labels: PR: reviewed-approved, Ready For Review

#300 Feature/storybook logo
  src/components/Header/index.jsx
  src/components/Logo/index.jsx
  src/components/MainNavigation/index.jsx
  src/stories/Logo.stories.js
Labels: PR: reviewed-approved, Ready For Review

#302 Fix/Logo-StoryBook
  src/stories/Logo.stories.js
Labels: PR: reviewed-approved

#295 StoryBook: HeaderCarousel
  src/components/Header/index.jsx
  src/components/HeaderCarousel/index.js
  src/stories/9-HeaderCarousel.stories.js
Labels: PR: reviewed-approved, Ready For Review

#301 StoryBook: Navigation
  src/components/HeaderCarousel/index.js
  src/components/MainNavigation/index.jsx
  src/stories/MainNavigation.stories.js
Labels: PR: reviewed-approved

#307 Fix activities bug
  src/components/Activities/index.jsx
  src/components/NavigationLink/index.jsx
Labels: PR: reviewed-approved

#306 Fix/featured banner Storybook
  src/stories/6-FeaturedBanner.stories.js
Labels: PR: reviewed-approved, Ready For Review

#309 Fix/StoryBook:Navigation
  src/components/Logo/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#304 StoryBook: WorkStyleCard
  src/components/WorkStyle/index.jsx
  src/components/WorkStyleCard/index.jsx
  src/stories/WorkStyleCard.stories.js
Labels: PR: reviewed-approved, Ready For Review

#299 Feature/news story
  src/App.js
  src/components/Article/index.jsx
  src/components/NewsAndArticles/index.jsx
  src/stories/News.stories.js
Labels: PR: reviewed-approved, Ready For Review

#286 Storybook/contact info
  src/App.js
  src/components/ContactInfo/index.jsx
  src/stories/ContactInfo.stories.js
Labels: PR: reviewed-approved, Ready For Review

#296 Added upcoming events storybook
  src/App.js
  src/components/FeaturedCause/MyLoader.jsx
  src/components/FeaturedCause/img/bg_2.png
  src/components/FeaturedCause/index.jsx
  src/components/FeaturedCause/style.css
  src/components/UpcomingEvents/MyLoader.jsx
  src/components/UpcomingEvents/index.jsx
  src/stories/18-upcomingEvents.stories.js
  src/stories/19-FeaturedCause.stories.js
  src/stories/20-Event.stories.js
Labels: PR: reviewed-approved, Ready For Review

#288 Storybook/testimonials
  src/App.js
  src/components/Testimonials/index.js
  src/stories/Testimonials.stories.js
Labels: PR: reviewed-approved, Ready For Review

#319 Fix/StoryBook Workstyle Card
  src/components/WorkStyle/index.jsx
  src/components/WorkStyleCard/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#315 Articles page/volunteering Banner
  src/components/VolunteeringBanner/img/blocks.png
  src/components/VolunteeringBanner/img/blocks.svg
  src/components/VolunteeringBanner/index.jsx
  src/components/VolunteeringBanner/styles.css
  src/stories/VolunteeingBanner.stories.js
Labels: PR: reviewed-approved

#325 Fix/infinite render in some componenets
  src/App.js
  src/components/Article/index.jsx
  src/components/Causes/index.jsx
  src/components/FeaturedCause/index.jsx
  src/components/NewsAndArticles/index.jsx
Labels: PR: reviewed-approved, bug

#321 fixed alignment bug
  src/components/ArticleBanner/index.js
  src/components/ArticleBanner/styles.css
Labels: PR: partially-approved, Ready For Review

#320 Feature/article page
  src/components/ArticleDetails/Loader.jsx
  src/components/ArticleDetails/index.js
  src/components/ArticleDetails/styles.css
  src/stories/TheArticle.stories.js
Labels: PR: reviewed-approved

#328 Changing image to thumbnail
  src/components/Footer/Articles/index.jsx
  src/components/NewsAndArticles/index.jsx
Labels: PR: reviewed-approved

#338 add Unique Key to WorkStyle
  src/components/WorkStyle/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#333 add ContactInfo unique key
  src/components/ContactInfo/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#323 Feature/widget
  package.json
  src/components/UpcomingEvents/index.jsx
  src/components/shared/Widget/index.jsx
  src/components/shared/Widget/style.scss
  src/stories/Widget.stories.js
  yarn.lock
Labels: PR: partially-approved

#336 fix-Feature/article page
  src/components/ArticleDetails/index.js
Labels: PR: reviewed-approved

#332 edit numbers section
  src/components/Numbers/index.jsx
  src/components/Numbers/style.css
Labels: PR: unreviewed, Ready For Review

#341 Static search component
  src/components/ArticlesSearch/index.jsx
  src/components/ArticlesSearch/style.scss
  src/components/shared/SearchBar/index.jsx
  src/stories/ArticlesSearch.stories.js
  src/stories/SearchBar.stories.js
Labels: PR: reviewed-approved, Ready For Review

#342 Feature/categories
  src/components/ArticlesCategories/index.jsx
  src/components/ArticlesCategories/myLoader.jsx
  src/components/ArticlesCategories/style.scss
  src/components/Categories/index.jsx
  src/components/Categories/myLoader.jsx
  src/components/Categories/style.scss
  src/components/shared/Category/index.jsx
  src/stories/ArticlesCategories.stories.js
  src/stories/Category.stories.js
Labels: PR: reviewed-approved, Ready For Review

#345 used pages CT to dsiplay links that will navigate to website pages
  src/components/MainNavigation/index.jsx
Labels: PR: reviewed-approved

#344 Introduce react router
  package.json
  src/App.js
  src/components/NavigationLink/index.jsx
  src/containers/Home/Home.jsx
  yarn.lock
Labels: PR: reviewed-approved, Ready For Review

#346 added published parameters to the end point
  src/components/MainNavigation/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#340 Article page content Container
  src/App.js
  src/components/Pages/ArticleDetails/index.jsx
  src/components/shared/Widget/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#343 Added Listof component
  src/Helpers/Helpers.jsx
  src/components/RecentArticles/index.jsx
  src/components/RecentArticles/myLoader.jsx
  src/components/shared/ListItemWithThumbnail/index.jsx
  src/components/shared/ListItemWithThumbnail/style.scss
  src/stories/ListItemWithThumbnail.stories.js
  src/stories/RecentArticles.stories.js
Labels: PR: reviewed-approved, Ready For Review

#351 Feature/add article storybook
  src/components/Article/index.jsx
  src/components/Article/style.css
  src/components/NewsAndArticles/index.jsx
  src/components/NewsAndArticles/styles.css
  src/stories/SingleArticle.stories.js
Labels: PR: reviewed-approved, Ready For Review

#352 Separate header component
  src/App.js
  src/components/Header/index.jsx
  src/components/HeaderCarousel/index.js
  src/components/MainNavigation/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#356 Create Home container
  src/App.js
  src/components/Welcome/index.jsx
  src/containers/Home/Home.jsx
  src/containers/Home/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#350 Fix/Articles page styling
  src/components/ArticleBanner/index.js
  src/components/ArticleBanner/styles.css
  src/components/ArticleDetails/index.js
  src/components/MainNavigation/style.css
  src/components/NavigationLink/index.jsx
  src/components/NavigationLink/style.css
  src/components/Pages/ArticleDetails/index.jsx
  src/components/RecentArticles/index.jsx
  src/components/VolunteeringBanner/index.jsx
  src/components/VolunteeringBanner/styles.css
  src/components/shared/ListItemWithThumbnail/index.jsx
  src/components/shared/ListItemWithThumbnail/style.scss
  src/stories/ArticleBanner.stories.js
  src/stories/RecentArticles.stories.js
  tailwind.config.js
Labels: PR: partially-approved, Ready For Review

#359 Bugfix/Recent articles list item title
  src/components/ArticleDetails/index.js
  src/components/Pages/ArticleDetails/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#360 Single Article page container
  src/App.js
  src/components/ArticleBanner/index.js
  src/containers/ArticleDetails/index.jsx
Labels: PR: reviewed-approved

#363 Fetch articlePage components data
  src/components/VolunteeringBanner/index.jsx
  src/containers/ArticleDetails/index.jsx
Labels: PR: reviewed-approved

#364 Feature/add articles page
  src/App.js
  src/components/Article/index.jsx
  src/components/ArticleDetails/index.js
  src/components/ArticlePageContent/index.jsx
  src/components/NewsAndArticles/index.jsx
  src/containers/ArticleDetails/index.jsx
  src/containers/Articles/index.jsx
Labels: PR: reviewed-approved

#366 Edit article model
  package.json
  src/components/ArticleDetails/Loader.jsx
  src/components/ArticleDetails/styles.css
  src/components/ArticleModel/Loader.jsx
  src/components/ArticleModel/index.js
  src/components/ArticleModel/styles.css
  src/components/ArticlePageContent/index.jsx
  src/containers/Articles/index.jsx
  src/stories/SingleArticle.stories.js
  src/stories/TheArticle.stories.js
  yarn.lock
Labels: PR: reviewed-approved, Ready For Review

#371 changing fetching data to fetch only the 3 recent articles
  src/components/RecentArticles/index.jsx
Labels: PR: reviewed-approved, Ready For Review

#372 Bugfix/article animation
  src/components/Article/index.jsx
  src/components/NewsAndArticles/index.jsx
Labels: PR: reviewed-approved
