Repository m3ntorship/charity, pull requests merged in 2020-04, with the labels that each got.

#10 Added a CSS file for every section
  dist/assets/css/activities.css
  dist/assets/css/causes.css
  dist/assets/css/donation-banner.css
  dist/assets/css/feedback.css
  dist/assets/css/footer.css
  dist/assets/css/global.css
  dist/assets/css/header.css
  dist/assets/css/main.css
  dist/assets/css/news.css
  dist/assets/css/numbers.css
  dist/assets/css/sponsors.css
  dist/assets/css/upcoming-events.css
  dist/assets/css/welcome.css
  dist/assets/css/work-style.css
  dist/index.html
Labels: Ready For Review

#9 add typography preview file
  dist/typography.html
Labels: Ready For Review

#11 install dependencies & build dist before deploying
  .github/workflows/deploy-firebase-live.yml
  .github/workflows/deploy-firebase-user.yml
Labels: Ready For Review

#13 Introducing tailwind
  dist/assets/css/global.css
  dist/assets/css/main.css
  tailwind.config.js
  tailwind.css
Labels: Ready For Review

#16 CSS Files directory change and introducing postcss-import
  .gitignore
  dist/assets/css/work-style.css
  dist/index.html
  package-lock.json
  package.json
  postcss.config.js
  src/css/activities.css
  src/css/causes.css
  src/css/donation-banner.css
  src/css/feedback.css
  src/css/footer.css
  src/css/global.css
  src/css/header.css
  src/css/main.css
  src/css/news.css
  src/css/numbers.css
  src/css/sponsors.css
  src/css/upcoming-events.css
  src/css/welcome.css
  src/css/work-style.css
  tailwind.config.js
Labels: Ready For Review

#24 Add several btn
  dist/typography.html
  src/css/global.css
Labels: Ready For Review

#25 Solve btn redundant styles and Add bg-colors classes to typography file
  dist/typography.html
  package-lock.json
  package.json
  postcss.config.js
  src/css/global.css
Labels: Ready For Review

#26 Introducing purgecss and nanocss
  .github/workflows/deploy-firebase-live.yml
  .github/workflows/deploy-firebase-user.yml
  package-lock.json
  package.json
  postcss.config.js
  src/css/main.css
Labels: PR: reviewed-approved

#19 create logo and contact section
  dist/assets/img/logo section/Logo@1X.png
  dist/assets/img/logo section/icon-1.png
  dist/assets/img/logo section/icon-2.png
  dist/assets/img/logo section/icon-3.png
  dist/index.html
  package-lock.json
Labels: PR: reviewed-approved, Ready For Review

#28 Style donation banner button
  dist/index.html
Labels: PR: partially-approved

#23 Our Popluar Causes Section
  dist/assets/img/causes/Thumbs.db
  dist/assets/img/causes/blocks.png
  dist/assets/img/causes/causes-card1.jpg
  dist/assets/img/causes/causes-card2.jpg
  dist/assets/img/causes/causes-card3.jpg
  dist/assets/img/causes/goal-icon.png
  dist/assets/img/causes/raised-icon.png
  dist/index.html
  package-lock.json
  src/css/causes.css
  src/img/causes/Thumbs.db
  src/img/causes/causes-card1.jpg
  src/img/causes/causes-card2.jpg
  src/img/causes/causes-card3.jpg
  src/img/causes/goal-icon.png
  src/img/causes/raised-icon.png
Labels: PR: reviewed-approved, Ready For Review

#29 Sponsers
  dist/assets/img/contact-footer/location.png
  dist/assets/img/contact-footer/mail.png
  dist/assets/img/contact-footer/phone.png
  dist/assets/img/sponsers/envato-dark.png
  dist/assets/img/sponsers/envato-light.png
  dist/index.html
  src/css/sponsors.css
Labels: PR: partially-approved, Ready For Review

#31 Container global class changes & tailwind utilities overriding global
  src/css/global.css
  src/css/main.css
Labels: PR: reviewed-approved, Ready For Review

#17 Feature/welcome
  dist/assets/img/welcome/back-pattern.png
  dist/assets/img/welcome/children.jpg
  dist/assets/img/welcome/rect-dots.png
  dist/assets/img/welcome/tri-dots.png
  dist/index.html
  src/css/welcome.css
Labels: PR: reviewed-approved, Ready For Review

#32 Feature/numbers
  dist/index.html
  src/css/numbers.css
Labels: PR: partially-approved, Ready For Review

#14 News and articles Section
  dist/index.html
  src/css/news.css
Labels: PR: reviewed-approved, Ready For Review

#20 Footer-Section
  dist/assets/icons/send.svg
  dist/assets/img/footer/hands.png
  dist/assets/imgs/footer-news-2.jpg
  dist/assets/imgs/footer-news.jpg
  dist/index.html
  src/css/footer.css
  tailwind.config.js
Labels: PR: reviewed-approved, Ready For Review

#35 Buttons Hover Effect
  src/css/global.css
Labels: PR: reviewed-approved, Ready For Review

#12 people's feedback section in html
  dist/index.html
  src/css/feedback.css
Labels: PR: reviewed-approved, Ready For Review

#36 Sponsers
  dist/index.html
  src/css/sponsors.css
Labels: PR: partially-approved

#38 edit button's font-weight
  dist/assets/css/main.css
  dist/index.html
Labels: PR: reviewed-approved

#40 Temporary git ignore fix
  .gitignore
  dist/assets/css/main.css
Labels: PR: reviewed-approved, Ready For Review

#30 Work style section
  dist/assets/img/work-style/01.svg
  dist/assets/img/work-style/02.svg
  dist/assets/img/work-style/03.svg
  dist/assets/img/work-style/04.svg
  dist/assets/img/work-style/blocks.png
  dist/assets/img/work-style/dots.png
  dist/assets/img/work-style/hover-pic-2.jpg
  dist/index.html
  src/css/global.css
  src/css/work-style.css
Labels: PR: merged, Ready For Review

#41 News section responsive
  dist/assets/css/main.css
  dist/index.html
  src/css/news.css
Labels: PR: reviewed-approved, Ready For Review

#42 Fix work style
  dist/index.html
  src/css/work-style.css
Labels: PR: reviewed-approved, Ready For Review

#44 removed main.css from master again
  dist/assets/css/main.css
Labels: PR: reviewed-approved

#45 fix: global styles
  dist/index.html
  src/css/global.css
Labels: PR: reviewed-approved, Ready For Review

#46 Fix logo contact
  dist/index.html
  src/css/header.css
Labels: PR: reviewed-approved

#47 changed font-size and border width to match psd
  dist/index.html
  src/css/donation-banner.css
Labels: PR: reviewed-approved, Ready For Review

#48 fix: spacing in how we work section
  src/css/work-style.css
Labels: PR: reviewed-approved

#49 fix popular causes section issues
  dist/index.html
  src/css/causes.css
Labels: PR: reviewed-approved, Ready For Review

#50 Fix: people-feedback & work-style
  dist/index.html
  src/css/feedback.css
  src/css/work-style.css
Labels: PR: reviewed-approved, Ready For Review

#53 Feature/react
  package.json
  public/index.html
  src/App.js
  src/clients/charity.js
  src/clients/index.js
  src/components/Logo/img/logo.png
  src/components/Logo/index.jsx
  src/components/Logo/styles.scss
  src/components/MainContact/img/icon-1.png
  src/components/MainContact/img/icon-2.png
  src/components/MainContact/img/icon-3.png
  src/components/MainContact/index.jsx
  src/components/MainContact/styles.scss
  src/index.js
  todo.md
  yarn.lock
Labels: PR: unreviewed

#55 use environment-based strapi url
  .github/workflows/deploy-firebase-live.yml
  .github/workflows/deploy-firebase-user.yml
  src/clients/charity.js
Labels: PR: unreviewed

#56 establish heroku app review deploymets
  .firebase/hosting.YnVpbGQ.cache
  .gitignore
  Procfile
  app.json
  package.json
  yarn.lock
Labels: PR: unreviewed

#58 Featured banner react
  package-lock.json
  src/App.js
  src/components/FeaturedBanner/index.jsx
  static/src/css/donation-banner.css
Labels: PR: reviewed-approved

#60 Feature/react contact top
  src/App.js
  src/clients/charity.js
  src/components/ContactTop/index.jsx
  src/components/ContactTop/style.scss
  yarn.lock
Labels: PR: reviewed-approved, Ready For Review

#66 Contact info react
  src/App.js
  src/components/ContactInfo/index.jsx
  src/components/ContactInfo/styles.css
  src/components/FeaturedBanner/index.jsx
  src/css/original_assets/img/contact-footer/location.png
  src/css/original_assets/img/contact-footer/mail.png
  src/css/original_assets/img/contact-footer/phone.png
Labels: PR: reviewed-approved, Ready For Review

#54 Numbers Component
  src/App.js
  src/components/Causes/style.css
  src/components/Numbers/img/circle.png
  src/components/Numbers/img/dots.png
  src/components/Numbers/index.jsx
  src/components/Numbers/style.css
Labels: PR: reviewed-approved, Ready For Review

#62 Causes component
  src/App.js
  src/components/Causes/img/blocks.png
  src/components/Causes/img/goal-icon.png
  src/components/Causes/img/raised-icon.png
  src/components/Causes/index.jsx
  src/components/Causes/style.css
  src/css/original_assets/causes.css
Labels: PR: reviewed-approved

#73 Main navigation react
  src/App.js
  src/components/MainNavigation/index.jsx
  src/components/MainNavigation/style.css
  src/components/NavigationLink/index.jsx
  src/components/NavigationLink/style.css
Labels: PR: reviewed-approved, Ready For Review

#74 added style for Activities Component
  src/components/Activities/styles.css
Labels: PR: partially-approved

#64 React how we work
  src/App.js
  src/components/WorkStyle/img/work-style/blocks.png
  src/components/WorkStyle/img/work-style/dots.png
  src/components/WorkStyle/img/work-style/hover-pic-2.jpg
  src/components/WorkStyle/index.jsx
  src/components/WorkStyle/styles.css
  src/components/WorkStyleCard/index.jsx
Labels: PR: unreviewed

#68 Upcoming Events with react
  package.json
  src/App.js
  src/components/UpcomingEvents/img/bg_1.png
  src/components/UpcomingEvents/img/bg_2.png
  src/components/UpcomingEvents/index.jsx
  src/components/UpcomingEvents/styles.css
Labels: PR: reviewed-approved, Ready For Review

#76 Fix causes fields
  src/components/Causes/index.jsx
Labels: PR: reviewed-approved
